name: Collectables
main: com.fawkes.plugin.collectables.CollectablesPlugin
version: one
commands:
  showcase:
    description: See all of your collectables!
    usage: /showcase [player]
    permission: collectables.showcase
    aliases: [awards]
    permission-message: You don't have permission to do that!