name: Collectables
main: com.fawkes.plugin.collectables.CollectablesPlugin
version: 0.1-SNAPSHOT
commands:
  showcase:
    description: See all of your collectables!
    usage: /slap <player>
    permission: projectfun.slap
    aliases: [awards]
    permission-message: You don't have permission to do that!